build: unbreak manpages install path after a185d231a123
===> Checking for items in STAGEDIR missing from pkg-plist
Error: Orphaned: man1/wob.1
Error: Orphaned: man5/wob.ini.5
===> Checking for items in pkg-plist which are not in STAGEDIR
Error: Missing: share/man/man1/wob.1
Error: Missing: share/man/man5/wob.ini.5